run_config:
  author: MLDS Team
  version: 0.0.1
  description: Web APP
  dependencies: requirements.txt
  data_source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset
  output: "runs"

preprocess_data:
  input_file: 'data/train_data.csv'
  output_file: 'data/cleaned_train_data.csv'

  numeric_features:
    - 'age'
    - 'avg_glucose_level'
    - 'bmi'
  cat_features:
    - 'gender'
    - 'ever_married'
    - 'work_type'
    - 'Residence_type'
    - 'smoking_status'
  drop_features:
    - 'id'
    - 'heart_disease'
  target: 'stroke'

aws:
  upload: True
  bucket_name: cloud-engineer-bucket
  region_name: us-east-2