aws:
  bucket_name: cloud-engineer-bucket
  profile_name: mlds_ce
  region_name: us-east-2
  upload: true
evaluate_performance:
- AUC
- Accuracy
- Confusion Matrix
- Classification Report
preprocess_data:
  cat_features:
  - gender
  - ever_married
  - work_type
  - Residence_type
  - smoking_status
  drop_features:
  - id
  - stroke
  input_file: train_data.csv
  numeric_features:
  - age
  - avg_glucose_level
  - bmi
  output_file: cleaned_train_data.csv
  target: heart_disease
run_config:
  author: MLDS Team
  data_source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset
  dependencies: requirements.txt
  description: Predict heart stroke risks
  output: runs
  version: 0.0.1
score_model:
  initial_features:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
train_model:
  features_to_fit:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
  max_depth: 10
  n_estimators: 10
  test_size: 0.3
