run_config:
  author: MLDS Team
  version: 0.0.1
  description: Predict heart stroke risks
  dependencies: requirements.txt
  data_source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset
  output: "runs"

preprocess_data:
  numeric_features:
    - 'age'
    - 'avg_glucose_level'
    - 'bmi'
  cat_features:
    - 'gender'
    - 'ever_married'
    - 'work_type'
    - 'Residence_type'
    - 'smoking_status'
  drop_features:
    - 'id'
    - 'stroke'
  target: 'heart_disease'


train_model:
  test_size: 0.3
  n_estimators: 10
  max_depth: 10
  features_to_fit:
    - 'log_entropy'
    - 'IR_norm_range'
    - 'entropy_x_contrast'

score_model:
  initial_features:
    - 'log_entropy'
    - 'IR_norm_range'
    - 'entropy_x_contrast'

evaluate_performance:
  - 'AUC'
  - 'Accuracy'
  - 'Confusion Matrix' 
  - 'Classification Report'

aws:
  upload: True
  bucket_name: alx7243-test-1
  region_name: us-east-2