run_config:
  author: MLDS Team
  version: 0.0.1
  description: Predict heart stroke risks
  dependencies: requirements.txt
  data_source: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset
  output: "runs"

preprocess_data:
  input_file: 'data/train_data.csv'
  output_file: 'data/cleaned_train_data.csv'

  numeric_features:
    - 'age'
    - 'avg_glucose_level'
    - 'bmi'
  cat_features:
    - 'gender'
    - 'ever_married'
    - 'work_type'
    - 'Residence_type'
    - 'smoking_status'
  drop_features:
    - 'id'
    - 'heart_disease'
  target: 'stroke'

train_model:
  random_state: 1911
  test_size: 0.3
  n_estimators: 10
  max_depth: 10
  output_model: 'models/'
  model_filename: 'random_forest_model.pkl'

score_model:
  initial_features:
    - 'log_entropy'
    - 'IR_norm_range'
    - 'entropy_x_contrast'

evaluate_performance:
  - 'AUC'
  - 'Accuracy'
  - 'Confusion Matrix' 
  - 'Classification Report'

aws:
  upload: True
  profile_name: mlds_ce
  bucket_name: cloud-engineer-bucket
  region_name: us-east-2